### ISSUE TITLE
Integration Testing: Setup database

### ISSUE THREAD

**Issue by dominique-boerner** [Foxdeck/fox-deck#54]
## 😒 Background:
We want to ensure the quality of the API endpoints with the help of integration tests. To do this, a database containing predefined data must be started up. The tests then run via the API and ensure that the endpoints can create, edit and load data.

## 🤔 Describe the solution you'd like:
The idea is to pull up a second MySQL database via Docker and feed it with initial data. 

**Todos:**

- [ ] pull up a second MySQL Database via Docker
- [ ] create 5 different Users: (usernames: Username001 - Username005; password: username001 - username005)
- [ ] each user should have 10 folder resources
- [ ] each user should have 10 document resources

**Evaluation:**

* Usage of https://testcontainers.com/
